### ISSUE TITLE
The antonyms query rate Limit was reached. The querying process is entering a temporary hibernation mode. 

### ISSUE THREAD

**Issue by 14H034160212** [johnbumgarner/wordhoard#11]
Hi,

I got this query rate limit when I iteratively call the Antonyms and Synonyms functions. Does it work fine? What is the hibernation mode? If it matters, how can I avoid that issue. Thank you so much.
The antonyms query rate Limit was reached. The querying process is entering a temporary hibernation mode. 

Thanks.

**Comment by johnbumgarner** [comment]
_WordHoard_ has an embedded, but configurable rate limiter.  This functionally is designed to prevent a web service from being overwhelm by too many requests.  When a service is overwhelm it can lead to a _CloudFlare_ response or even IP address blacklisting.   When a rate limit is triggered the query service will go into a  temporary hibernation mode, which will reset after a given time.  This temporary hibernation mode is not configurable.  

Please reference the documentation for the parameters to modify the  rate limiter in _WordHoard_. 

https://github.com/johnbumgarner/wordhoard#rate-limiting

If you don't have any additional questions about the rate limiter please close this issue.

**Comment by johnbumgarner** [comment]
I'm closing this issue, if you have any additional questions about the rate limiter please open another issue.
