### ISSUE TITLE
find_definitions can returns antonyms

### ISSUE THREAD

**Issue by drewvid** [johnbumgarner/wordhoard#14]
Find definitions will sometimes return antonyms because the antonym cache is checked by mistake.

Returns
        ----------
        :return: list of definitions
        :rtype: list
        """
        valid_word = self._validate_word()
        if valid_word:
            check_cache = caching.cache_antonyms(self._word)

**Comment by johnbumgarner** [comment]
Thanks for pointing this out.  Let me look at this issue. 

Can you provide me a code sample?

**Comment by drewvid** [comment]
Sure.

from pprint import pprint
from wordhoard import Antonyms, Definitions

if __name__ == '__main__':

    # does not work
    word = "walk"
    antonyms = Antonyms(word).find_antonyms()
    definitions = Definitions(word).find_definitions()
    print("Antonyms: ", antonyms)
    print("Definitions: ", definitions)
    
    # works
    word = "talk"
    definitions = Definitions(word).find_definitions()
    antonyms = Antonyms(word).find_antonyms()
    print("Antonyms: ", antonyms)
    print("Definitions: ", definitions)

**Comment by drewvid** [comment]
I fixed the problem locally by editing line 150 in "dictionary.py":

was: check_cache = caching.cache_antonyms(self._word)
is now: check_cache = caching.cache_definition(self._word)

**Comment by johnbumgarner** [comment]
Thanks.  I will make this change and push out an update.  Is there anything else that this package is missing that would be useful?

**Comment by johnbumgarner** [comment]
This issue was fixed in WordHoard v1.5.2, which was pushed to GitHub this morning.  This release will be pushed to PyPi today.
