### ISSUE TITLE
Questionable behavior of find_synonyms()

### ISSUE THREAD

**Issue by Gorluxor** [johnbumgarner/wordhoard#19]
with the following code `generic_utils.py`:
```python
from wordhoard import Synonyms
def synonym(word):
    syn = Synonyms(word)
    syn_res = syn.find_synonyms()
    return syn_res
 ```
 ran from terminal with clean state:
 ```
 >>> import generic_utils as gu
>>> gu.synonym('mother')
['ma', 'mom', 'mum', 'dam', 'mama', 'mater', 'mommy', 'mummy', 'mamma', 'mammy', 'momma', 'parent', 'para i', 'supermom', 
'puerpera', 'old lady', 'old woman', 'primipara', 'quadripara', 'quintipara', 'birth mother', 'mother-in-law',
 'foster mother', 'female parent', 'surrogate mother', 'biological mother']
>>> gu.synonym('mother')
['noun']
 ```
env info with `wordhoard==1.5.3` and `python 3.10.10`:
```
backoff==2.2.1
beautifulsoup4==4.12.2
certifi==2022.12.7
charset-normalizer==3.1.0
cloudscraper==1.2.71
deckar01-ratelimit==3.0.2
deepl==1.14.0
idna==3.4
lxml==4.9.2
pyparsing==3.0.9
requests==2.28.2
requests-toolbelt==1.0.0
soupsieve==2.4.1
urllib3==1.26.15
```
Seems to be some error with **caching**; once was able to get some error message, but not 100% sure that this is it.
```
ERROR:wordhoard.synonyms:A KeyError occurred in the following code segment:
ERROR:wordhoard.synonyms:  File "/<path>/.conda/envs/sam/lib/python3.10/site-packages/wordhoard/synonyms.py", line 571, in _query_thesaurus_com
    self._update_cache(part_of_speech_category, synonyms_list)
  File "/<path>/.conda/envs/sam/lib/python3.10/site-packages/wordhoard/synonyms.py", line 134, in _update_cache
    caching.insert_word_cache_synonyms(self._word, pos_category, synonyms)
  File "/<path>/.conda/envs/sam/lib/python3.10/site-packages/wordhoard/utilities/caching.py", line 65, in insert_word_cache_synonyms
    temporary_dict_synonyms[word][pos_category] += deduplicated_values
```
Was able to fix behaviour, when disabling caching totally by changing the line https://github.com/johnbumgarner/wordhoard/blob/1e54f451ee2e1a896d5afc4ec399d3c2fc27c0f6/wordhoard/synonyms.py#L208 to
`check_cache = [False]`

**Comment by johnbumgarner** [comment]
I have never used `generic_utils`, so I need to look into what they do. 

this concerns me:

> gu.synonym('mother')
['noun']

and I need to create a python 3.10.10 environment to see what breaks.

The the reason that I use caching is to prevent redundant queries for words.  

I will look into this a get back to you.

**Comment by Gorluxor** [comment]
> I have never used generic_utils, so I need to look into what they do.

The code in `generic_utils.py` is provided in the issue. It is just a wrapper in the first code cell. 

> The the reason that I use caching is to prevent redundant queries for words.

I understand, but this is a quick and dirty fix until the caching works.

**Comment by johnbumgarner** [comment]
Where I execute this code in `Python 3.9.16` I get no errors in `wordhoard_error.yaml`

```python

from wordhoard import Synonyms
def synonym(word):
    syn = Synonyms(word)
    syn_res = syn.find_synonyms()
    return syn_res

words = ['mother', 'mother']
for word in words:
    results = synonym(word)
    print(results)
```

**Comment by Gorluxor** [comment]
Hmmm, I check `wordhoard_error.yaml` with the provided code, with no errors, but still the same behavior with `python 3.10.10` (sadly would be thought to change as already have a lot of different libraries for this version):
```
['ma', 'mum', 'dam', 'mom', 'mama', 'mommy', 'momma', 'mater', 'mammy', 'mamma', 'mummy', 'parent', 'para i', 'old lady', 'puerpera', 'supermom', 'primipara', 'old woman', 'quadripara', 'quintipara', 'birth mother', 'female parent', 'mother-in-law', 'foster mother', 'surrogate mother', 'biological mother']
['noun']
```

**Comment by Gorluxor** [comment]
Check with the debugger, 
https://github.com/johnbumgarner/wordhoard/blob/1e54f451ee2e1a896d5afc4ec399d3c2fc27c0f6/wordhoard/synonyms.py#L210
`check_cache[1]` has the following value:
```python
{'noun': ['mom', 'parent', 'female parent', 'momma', 'mama', 'mammy', 'mommy', 'ma', 'mom', ...]}
```
That is where the `noun` comes from

**Comment by johnbumgarner** [comment]
Yes, `noun` is the part_of_speech.   I need to create a `Python 3.10.10` to see what errors I get.

**Comment by johnbumgarner** [comment]
So the problem is related to `Python 3.10.10`.  I need to rework the code to support `Python 3.10.10`.  I will post an update here when I have fixed this issue.

**Comment by Gorluxor** [comment]
@johnbumgarner I have made a PR. It does seem questionable why you don't pass the `synonyms` variable that is passed in 2 other format types.

**Comment by johnbumgarner** [comment]
what does this mean _it does seem questionable why you don't pass the synonyms variable that is passed in 2 other format types._

**Comment by Gorluxor** [comment]
https://github.com/johnbumgarner/wordhoard/blob/1e54f451ee2e1a896d5afc4ec399d3c2fc27c0f6/wordhoard/synonyms.py#L207-L222
In the provided snippet of the current version of `find_synonyms`.
We can observe that we have 3 code paths based on `self._output_format`. 
Only in the list case do we provide `check_cache[1]`, in the JSON and dict return types we return newly create `synonyms` variable, which already holds the required information.

**Comment by johnbumgarner** [comment]
I believe that the issue in the code below, because the `dictionary` and `json` code works.

```python
part_of_speech = list(check_cache[1].keys())[0] 
         synonyms = cleansing.flatten_multidimensional_list(list(check_cache[1].values())) 
         if self._output_format == 'list': 
             return sorted(set([word.lower() for word in check_cache[1]])) 
```

**Comment by Gorluxor** [comment]
Totally agree, the issue is in `check_cache[1]`, instead should be `synonyms`, as discussed in the previous comment and the PR.

**Comment by johnbumgarner** [comment]
This is correct.  I see that I need to do more testing before pushing out a new release. Thanks for finding this bug.
