### ISSUE TITLE
Missing PYPI_description.md from github

### ISSUE THREAD

**Issue by Gorluxor** [johnbumgarner/wordhoard#20]
https://github.com/johnbumgarner/wordhoard/blob/1e54f451ee2e1a896d5afc4ec399d3c2fc27c0f6/setup.py#L3-L4

Produces an error when installing with 
```
pip install -e .
```
Because the file (`PYPI_description.md`) does not exist in the repository. 
Fix without having the file would be to comment it out and add 
`long_description = "temp description"`

**Comment by johnbumgarner** [comment]
I will add the `PYPI_description.md` to the repository once I fix the other issue.

**Comment by johnbumgarner** [comment]
I will add the PYPI_description.md to the repository later today.
