### ISSUE TITLE
Amazing!

### ISSUE THREAD

**Issue by zarkua** [johnbumgarner/wordhoard#26]
hehey, this is amazing. Is there a chanse to get all words from database in style
Hypernymy: hyponims?

**Comment by johnbumgarner** [comment]
Thanks.  What do you mean by all words?

**Comment by zarkua** [comment]
for example, there is no Hypernymy like "water sports". But is there anywhere list of Hypernymies that I could use? Like horses, dogs, ships, old movies etc

**Comment by johnbumgarner** [comment]
I'm sorry, but there is not a detailed list of all English hypernyms or hyponyms.  I wish that there was a comprehensive list somewhere that I could also use.  

I'm interested to know how you're using WordHoard.  Feedback helps me improve the module for others to use. 

P.S.  Don't forgot to Star this Repository ;-}
