### ISSUE TITLE
Consider including provenance with results in development mode

### ISSUE THREAD

**Issue by ngray77** [johnbumgarner/wordhoard#4]
The documentation outlines that multiple sources are used, but it's unclear what the provenance might be for any particular result, or whether a particular operation will generate network traffic or reference the local pickle files. Suggest a dev mode with more provenance.

**Comment by johnbumgarner** [comment]
I don't under this issue.  Can you provide more details on what you mean?

**Comment by ngray77** [comment]
As a consumer when a list of results come back, and one looks spurious, it's not clear where it came from. Dictionary.com? Who knows. Including some attributes or columns with the results that point users to the provenance of the result would let them decide what to do next. Probably never necessary for runtime workloads.

**Comment by johnbumgarner** [comment]
I understand your point now.  I could return a dictionary that has the sources as the keys. I will explore on how to do this and provide a list if requested.

**Comment by johnbumgarner** [comment]
I understand your point now.  I could return a dictionary that has the sources as the keys. I will explore on how to do this and provide a list if requested.
