### ISSUE TITLE
Consider allowing for design-time and runtime configurability of sources

### ISSUE THREAD

**Issue by ngray77** [johnbumgarner/wordhoard#5]
No configuration appears to be available that would allow consumers to specify which source datasets to use. Antonyms for instance uses _query_synonym_com _query_thesaurus_com _query_thesaurus_plus, and it would be helpful to be able to suppress each in configuration or runtime. Additionally, the ability to leverage a local override set would be helpful in some cases.

**Comment by johnbumgarner** [comment]
This capability was in the previous version, but it was removed for ease of use for a user to call multiple sources at once.  I could add this functionally back .   I could add a source constructor  to the that class.  I will explore how this would work for certain classes.
