### ISSUE TITLE
Synonyms discovery is a bit of a mystery

### ISSUE THREAD

**Issue by ngray77** [johnbumgarner/wordhoard#6]
After reviewing synonyms_discovery_aggregation to better understand how the proprietary dataset is being created, the location of any actual source code is unclear, as well as where the results are being stored in wordhoard (pickle files?). 

Recommend offering the code as a dataset builder that customers can change and build their own pickle files for wordhoard. Ideally following a data science pipeline format such as https://drivendata.github.io/cookiecutter-data-science/.

**Comment by johnbumgarner** [comment]
The data harvested is stored in an in-memory cache.  This cache is only maintained for a single session.  I could add a function to write data to a local pickle, which could be queried prior to querying a source.  Doing this could reduce queries to an online source.   Is this what you're thinking?

**Comment by ngray77** [comment]
I'm inferring from the readme, synonyms_discovery_aggregation, and the existence of pickle files that some proprietary set (not an ephemeral cache) helps power the tool in addition to the online sources. If I'm mistaken, close this.

**Comment by johnbumgarner** [comment]
I will updated the README with more information related to the caching and pickle files.
